apiVersion: v1
kind: Service
metadata:
  name: legacy-insurer-portal-service
spec:
  selector:
    app: legacy-insurer-portal
  ports:
  - protocol: TCP
    nodePort: 30100
    targetPort: 3000
  type: NodePort