apiVersion: v1
kind: Service
metadata:
  name: modern-insurer-portal-service
spec:
  selector:
    app: modern-insurer-portal
  ports:
  - protocol: TCP
    port: 30100
    targetPort: 3000
  type: LoadBalancer