apiVersion: v1
kind: Service
metadata:
  name: mainframe-simulator-service
spec:
  selector:
    app: mainframe-simulator
  ports:
  - protocol: TCP
    port: 30101
    targetPort: 8080
  type: LoadBalancer
